/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kantorwalut;

/**
 *
 * @author matys
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelChoose = new javax.swing.JLabel();
        jComboBoxChoose = new javax.swing.JComboBox<>();
        jLabelInputZL = new javax.swing.JLabel();
        jTextFieldMoney = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldInputZL = new javax.swing.JTextField();
        jButtonBuy = new javax.swing.JButton();
        jButtonSell = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kantor Walut");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setText("Kantor Walut");

        jLabelChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChoose.setText("Wybierz walutę:");

        jComboBoxChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "GBP", "CHF", "JPY" }));

        jLabelInputZL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInputZL.setText("Ilość pieniędzy w ZŁ:");

        jTextFieldMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoneyActionPerformed(evt);
            }
        });

        jLabel1.setText("Ilość pieniędzy które otrzymasz lub chcesz sprzedać:");

        jTextFieldInputZL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldInputZL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputZLActionPerformed(evt);
            }
        });

        jButtonBuy.setText("Kup");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });

        jButtonSell.setText("Sprzedaj");
        jButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellActionPerformed(evt);
            }
        });

        jButtonClear.setText("Wyczyść");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldInputZL)
                        .addComponent(jTextFieldMoney)
                        .addComponent(jComboBoxChoose, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelInputZL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInputZL)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldInputZL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoneyActionPerformed

    private void jTextFieldInputZLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputZLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInputZLActionPerformed

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        SaveToFile save = new SaveToFile();
        Get get = new Get();
        Calculate calc = new Calculate();
        String currency = (String) jComboBoxChoose.getSelectedItem();
        get.category(currency);
        get.getCurrencyvalueBuy();
        if(jTextFieldInputZL.getText().isBlank()||jTextFieldInputZL.getText()==null||!jTextFieldInputZL.getText().matches("[0-9]+")){
            jTextFieldInputZL.setText("Proszę podać dodatnią liczbę");
        }else{
            int moneyInput = Integer.parseInt(jTextFieldInputZL.getText());
            if(moneyInput<=0){
                jTextFieldInputZL.setText("Proszę podać dodatnią liczbę");
            }else{
                float currencyCalc = get.getCurrency();
                double currencyVal = calc.getMoneyBuy(moneyInput,currencyCalc);
                currencyVal = Math.floor(currencyVal * 100) / 100;
                jTextFieldMoney.setText(""+currencyVal+" "+currency);
                save.saveToFileBuy(moneyInput, currencyVal,currency);
            }
        }
    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void jButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellActionPerformed
        SaveToFile save = new SaveToFile();
        Get get = new Get();
        Calculate calc = new Calculate();
        String currency = (String) jComboBoxChoose.getSelectedItem();
        get.category(currency);
        get.getCurrencyvalueSell();
        if(jTextFieldMoney.getText().isBlank()||jTextFieldMoney.getText()==null||!jTextFieldMoney.getText().matches("[0-9]+")){
            jTextFieldMoney.setText("Proszę podać dodatnią liczbę");
        }else{
            int moneyInput = Integer.parseInt(jTextFieldMoney.getText());
            if(moneyInput<=0){
                jTextFieldMoney.setText("Proszę podać dodatnią liczbę");
            }else{
                float currencyCalc = get.getCurrency();
                double currencyVal = calc.getMoneySell(moneyInput,currencyCalc);
                currencyVal = Math.floor(currencyVal * 100) / 100;
                jTextFieldInputZL.setText("Otrzymasz: "+currencyVal+" zł");
                save.saveToFileSell(moneyInput, currencyVal,currency);
            }
        }
        
    }//GEN-LAST:event_jButtonSellActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldInputZL.setText("");
        jTextFieldMoney.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSell;
    private javax.swing.JComboBox<String> jComboBoxChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChoose;
    private javax.swing.JLabel jLabelInputZL;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldInputZL;
    private javax.swing.JTextField jTextFieldMoney;
    // End of variables declaration//GEN-END:variables
}
